from __future__ import annotations

import argparse
import logging
import os
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
from datasets import Dataset
from dotenv import load_dotenv
from huggingface_hub import create_repo, upload_file

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")


@dataclass(frozen=True)
class DatasetSpec:
    local_path: Path
    repo_id: str
    title: str
    description: str
    has_target: bool


ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT / "data"


def read_table(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, index_col=0)
    df = df.reset_index(names="frame_id")
    return df


def build_readme(spec: DatasetSpec, df: pd.DataFrame) -> str:
    target_note = (
        "- `iou`: mean IoU for the scene\n"
        "- `lrp`: LRP for the scene\n\n"
        "Use either target column downstream depending on the assessor task.\n"
        if spec.has_target
        else "This dataset does not include a prediction target. It is intended as a feature-only baseline.\n"
    )

    columns = "\n".join(f"- `{column}`" for column in df.columns)

    return f"""---
dataset_info:
  description: {spec.description}
---

# {spec.title}

{spec.description}

## Source

- Extracted from the validation split of the ZOD frames dataset
- One row per scene/frame
- `frame_id` keeps the original ZOD frame identifier

## Contents

{target_note}## Columns

{columns}

## Notes

- The tabular features are the meta-features computed in this repository.
- The detector-specific datasets include both detector quality targets so that you can choose the target metric later.
"""


def upload_dataset(spec: DatasetSpec, token: str, namespace: str, private: bool) -> None:
    """Upload dataset using the datasets library with built-in resumability and chunking."""
    df = read_table(spec.local_path)
    repo_id = f"{namespace}/{spec.repo_id}"

    logger.info(f"Creating/accessing repo: {repo_id}")
    create_repo(repo_id, repo_type="dataset", token=token, exist_ok=True, private=private)

    logger.info(f"Loading {spec.local_path.name} ({len(df)} rows) into Dataset...")
    dataset = Dataset.from_pandas(df)

    logger.info(f"Uploading {spec.repo_id} to Hugging Face...")
    try:
        dataset.push_to_hub(
            repo_id=repo_id,
            token=token,
            private=private,
        )
    except TypeError as e:
        # datasets can successfully upload the parquet shard(s) and then fail while
        # trying to update an empty repo's dataset card metadata (repo_info.splits is None).
        # Treat that specific bug as non-fatal.
        if "NoneType" in str(e) and "iterable" in str(e):
            logger.warning(
                "Dataset shard upload completed, but Hugging Face failed to update the autogenerated card metadata. "
                "Continuing with our own README upload."
            )
        else:
            raise

    # Upload README with dataset card
    logger.info(f"Uploading dataset card...")
    readme_content = build_readme(spec, df)
    
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False) as f:
        f.write(readme_content)
        f.flush()
        temp_path = f.name
    
    try:
        upload_file(
            path_or_fileobj=temp_path,
            path_in_repo="README.md",
            repo_id=repo_id,
            repo_type="dataset",
            token=token,
        )
    finally:
        os.unlink(temp_path)

    logger.info(f"✓ Successfully uploaded {spec.local_path.name} -> {repo_id}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Upload the ZOD meta-feature tables to Hugging Face as separate datasets."
    )
    parser.add_argument("--namespace", default="femartip", help="Hugging Face namespace / username or org.")
    parser.add_argument("--token", default=os.environ.get("HF_TOKEN"), help="Hugging Face token. Defaults to HF_TOKEN.")
    parser.add_argument("--private", action="store_true", help="Create the dataset repos as private.")
    return parser.parse_args()


def main():
    # Enable hf_transfer for faster uploads if available
    if "HF_HUB_ENABLE_HF_TRANSFER" not in os.environ:
        os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"
    
    load_dotenv()
    args = parse_args()

    if not args.token:
        raise ValueError("Missing Hugging Face token. Set HF_TOKEN or pass --token.")

    logger.info(f"Uploading to namespace: {args.namespace}")
    logger.info(f"Private repos: {args.private}")

    specs = [
        DatasetSpec(
            local_path=DATA_DIR / "metafeatures.csv",
            repo_id="zod-metafeatures",
            title="ZOD validation meta-features",
            description="Feature-only table built from meta-features extracted from the ZOD validation split.",
            has_target=False,
        ),
        DatasetSpec(
            local_path=DATA_DIR / "faster-rcnn_metafeatures.csv",
            repo_id="zod-faster-rcnn-metafeatures",
            title="ZOD validation meta-features + Faster R-CNN targets",
            description="Meta-features extracted from ZOD validation scenes with Faster R-CNN quality targets.",
            has_target=True,
        ),
        DatasetSpec(
            local_path=DATA_DIR / "yolo_metafeatures.csv",
            repo_id="zod-yolo-metafeatures",
            title="ZOD validation meta-features + YOLO targets",
            description="Meta-features extracted from ZOD validation scenes with YOLO quality targets.",
            has_target=True,
        ),
    ]

    for spec in specs:
        if not spec.local_path.exists():
            raise FileNotFoundError(f"Missing input file: {spec.local_path}")

    failed = []
    for i, spec in enumerate(specs, 1):
        try:
            logger.info(f"[{i}/{len(specs)}] Processing {spec.repo_id}")
            upload_dataset(spec, args.token, args.namespace, args.private)
        except Exception as e:
            logger.error(f"Failed to upload {spec.repo_id}: {e}")
            import traceback
            traceback.print_exc()
            failed.append(spec.repo_id)

    if failed:
        logger.error(f"\nFailed datasets ({len(failed)}/{len(specs)}): {', '.join(failed)}")
        raise RuntimeError(f"Upload failed for: {', '.join(failed)}")
    else:
        logger.info(f"\n✓ All {len(specs)} datasets uploaded successfully!")


if __name__ == "__main__":
    main()
